---
- name: Disable swap
  shell: swapoff -a
  ignore_errors: yes

- name: Remove swap entries in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/swapfile'
    state: absent

- name: Load necessary modules
  modprobe:
    name: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Configure sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }

- name: Install prerequisite packages
  apt:
    name: 
      - gnupg
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add Kubernetes apt-key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"
    force: true

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
    state: present
    update_cache: yes

- name: Install Kubelet
  apt:
    name: kubelet=1.31.*
    state: present
    update_cache: true

- name: Install Kubeadm
  apt:
    name: kubeadm=1.31.*
    state: present
    update_cache: true

- name: Enable kubelet and containerd
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - kubelet
    - containerd


