- name: Generate and configure SSH access on nodes
  hosts: all
  roles:
    - ssh_config

- name: Configure hostnames for all nodes
  hosts: all
  become: yes
  roles:
    - hostname_config 

- name: Install the latest version of containerd from the Docker repository
  hosts: all
  become: yes
  roles:
    - containerd_install

- name: Configure nodes for Kubernetes
  hosts: all
  become: yes
  roles:
    - nodes_setup

- name: Set up the control-plane
  hosts: control-plane
  become: yes
  remote_user: debian
  roles:
    - master_setup

- name: Create the node join token
  hosts: control-plane
  become: yes
  roles:
    - master_token

- name: Join the worker nodes
  hosts: worker
  become: yes
  remote_user: debian
  roles:
    - worker_join

- name: Install ArgoCD 
  hosts: control-plane  
  remote_user: debian
  become: yes
  roles:
    - argo_install
