- name: Générer et configurer l'accès SSH sur les nœuds
  hosts: all
  roles:
    - ssh_config

- name: Configurer les noms d'hôtes pour tous les noeuds
  hosts: all
  become: yes
  roles:
    - hostname_config 

- name: Installer la version récente de containerd depuis le dépôt Docker 
  hosts: all
  become: yes
  roles:
    - containerd_install

- name: Configurer les nœuds pour Kubernetes
  hosts: all
  become: yes
  roles:
    - nodes_setup

- name: Configurer le control-plane
  hosts: control-plane
  become: yes
  remote_user: debian
  roles:
    - master_setup

- name: Créer le token d'invitation des noeuds
  hosts: control-plane
  become: yes
  roles:
    - master_token

- name: Joindre les noeuds worker
  hosts: worker
  become: yes
  remote_user: debian
  roles:
    - worker_join

- name: Installer ArgoCD 
  hosts: control-plane  
  remote_user: debian
  become: yes
  roles:
    - argo_install 
   
    