version: '3.8'

services:
  app:
    build: .
    image: flask-app:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0

  tests:
    build: .
    image: flask-app:latest
    environment:
      - PYTHONPATH=/app
    command: ["pytest", "tests"]
