ssh_key_name: "id_rsa_k8s"  # Nom du fichier de la clé SSH
ssh_user: "debian"          # Utilisateur cible sur les machines cibles
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
local_user: "ansible"
ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
ssh_known_hosts: "{{ groups['all'] }}"
