ssh_key_name: "id_rsa_k8s"  # SSH Key file name
ssh_user: "debian"          # remote user on nodes
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
local_user: "ansible"
ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
ssh_known_hosts: "{{ groups['all'] }}"
