- name: S'assurer que le répertoire /etc/apt/keyrings existe
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Installer les paquets pré-requis
  apt:
    name: 
      - gnupg
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker apt-key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker-apt-keyring.asc
    mode: "0644"
    force: true

- name: Ajouter le dépôt Docker officiel
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker'

- name: Ajouter la clé GPG pour le dépôt Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Mettre à jour la liste des paquets
  apt:
    update_cache: yes

- name: Installer containerd 
  apt:
    name: containerd.io
    state: latest
    force_apt_get: yes
    allow_change_held_packages: true

- name: Vérifier si containerd est installé
  command: containerd --version
  register: containerd_version
  ignore_errors: yes

- name: Afficher la version de containerd installée
  debug:
    msg: "Version de containerd installée : {{ containerd_version.stdout }}"

- name: Vérifier si le répertoire /etc/containerd existe
  stat:
    path: /etc/containerd
  register: containerd_dir

- name: Créer le répertoire containerd 
  file:
    path: /etc/containerd
    state: directory
  when: "not containerd_dir.stat.exists"

- name: Ajoute la configuration containerd 
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml

- name: Modifier systemd_cgroup et SystemdCgroup à true dans le fichier config.toml (modifier si existe)
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)(systemd_cgroup|SystemdCgroup)\s*='
    line: '\1\2 = true'
    backrefs: yes
    create: yes
  notify: 
    - containerd_restart


