- name: Ensure the directory /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Install prerequisite packages
  apt:
    name: 
      - gnupg
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker apt-key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker-apt-keyring.asc
    mode: "0644"
    force: true

- name:  Add the official Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker'

- name: Add the GPG key for the Docker repository
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Update package list
  apt:
    update_cache: yes

- name: Install containerd 
  apt:
    name: containerd.io
    state: latest
    force_apt_get: yes
    allow_change_held_packages: true

- name: Check if containerd is installed
  command: containerd --version
  register: containerd_version
  ignore_errors: yes

- name: Display the installed containerd version
  debug:
    msg: "Version de containerd installée : {{ containerd_version.stdout }}"

- name: Check if /etc/containerd directory exists
  stat:
    path: /etc/containerd
  register: containerd_dir

- name: Create the containerd directory 
  file:
    path: /etc/containerd
    state: directory
  when: "not containerd_dir.stat.exists"

- name: Add containerd configuration 
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml

- name: Set systemd_cgroup and SystemdCgroup to true in config.toml (modify if exists)
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)(systemd_cgroup|SystemdCgroup)\s*='
    line: '\1\2 = true'
    backrefs: yes
    create: yes
  notify: 
    - containerd_restart


