- name: Enable TCP port 6443 for node connection 
  wait_for: 
    host: "{{ hostvars[groups['control-plane'][0]].ansible_host }}"
    port: 6443
    timeout: 1

- name: Check if the worker node is already a cluster member
  shell: "echo {{ inventory_hostname }}"
  register: worker_node_name

- name: Join worker nodes not present in the cluster
  shell: |
    systemctl daemon-reload && sudo systemctl stop kubelet || true
    {{ hostvars[groups['control-plane'][0]].join_command }} >> node_joined.log && sudo systemctl start kubelet
  args:
    chdir: /home/debian
  when: worker_node_name.stdout not in hostvars[groups['control-plane'][0]].cluster_nodes_list
