- name: Activer le port TCP 6443 pour la connection des noeuds 
  wait_for: 
    host: "{{ hostvars[groups['control-plane'][0]].ansible_host }}"
    port: 6443
    timeout: 1

- name: Vérifier si le noeud worker est déja membre du cluster
  shell: "echo {{ inventory_hostname }}"
  register: worker_node_name

- name: Joindre les noeuds worker absent du cluster
  shell: |
    systemctl daemon-reload && sudo systemctl stop kubelet || true
    {{ hostvars[groups['control-plane'][0]].join_command }} >> node_joined.log && sudo systemctl start kubelet
  args:
    chdir: /home/debian
  when: worker_node_name.stdout not in hostvars[groups['control-plane'][0]].cluster_nodes_list