- name: Scan the hosts in the inventory
  shell: "ssh-keyscan -H -t rsa {{ hostvars[item].ansible_host }} 2> /dev/null"
  with_items: "{{ ssh_known_hosts }}"
  register: ssh_known_host_results
  ignore_errors: yes
  delegate_to: localhost
  run_once: true

- name: Update the known_hosts file '{{ ssh_known_hosts_file }}'
  known_hosts:
    name: "{{ hostvars[item.item].ansible_host }}"
    key: "{{ item.stdout }}"
    path: "{{ ssh_known_hosts_file }}"
  when: item.stdout is defined 
  with_items: "{{ ssh_known_host_results.results }}"
  delegate_to: localhost
  run_once: true
  no_log: true

- name: Check if the private key already exists
  stat:
    path: "~/.ssh/{{ ssh_key_name }}"
  register: ssh_key_check
  delegate_to: localhost
  run_once: true


- name: Generate an SSH key pair
  command: "ssh-keygen -t rsa -b 2048 -f ~/.ssh/{{ ssh_key_name }} -q -N ''"
  when: not ssh_key_check.stat.exists
  delegate_to: localhost
  run_once: true

- name: Read the generated public key
  slurp:
    src: "~/.ssh/{{ ssh_key_name }}.pub"
  register: ssh_public_key
  delegate_to: localhost
  run_once: true

- name: Create the .ssh directory for the user
  file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
  become: yes

- name: Copy the SSH public key into authorized_keys
  copy:
    content: "{{ ssh_public_key['content'] | b64decode }}"
    dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0600'
  become: yes

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  become: yes

- name: Disable root access via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backup: yes
  become: yes

- name: Restart the SSH service
  systemd:
    name: ssh
    state: restarted
    enabled: yes
  become: yes

- name: Remove passwords in the inventory file
  replace:
    path: '{{ inipath }}/inventory.ini'
    regexp: 'ansible_.*password=debian'
    replace: ''
  delegate_to: localhost
  run_once: true
