# 0 Identifier les noeuds
- name: Scanner les hôtes dans l'inventaire
  shell: "ssh-keyscan -H -t rsa {{ hostvars[item].ansible_host }} 2> /dev/null"
  with_items: "{{ ssh_known_hosts }}"
  register: ssh_known_host_results
  ignore_errors: yes
  delegate_to: localhost
  run_once: true

- name: Mettre à jour le fichier known_host '{{ ssh_known_hosts_file }}'
  known_hosts:
    name: "{{ hostvars[item.item].ansible_host }}"
    key: "{{ item.stdout }}"
    path: "{{ ssh_known_hosts_file }}"
  when: item.stdout is defined 
  with_items: "{{ ssh_known_host_results.results }}"
  delegate_to: localhost
  run_once: true
  no_log: true
  


# 1. Générer une paire de clé SSH sur la machine locale si elle n'existe pas
- name: Vérifier si la clé privée existe déjà
  stat:
    path: "~/.ssh/{{ ssh_key_name }}"
  register: ssh_key_check
  delegate_to: localhost
  run_once: true


- name: Générer une paire de clés SSH
  command: "ssh-keygen -t rsa -b 2048 -f ~/.ssh/{{ ssh_key_name }} -q -N ''"
  when: not ssh_key_check.stat.exists
  delegate_to: localhost
  run_once: true

# 2. Lire la clé publique générée
- name: Lire la clé publique générée
  slurp:
    src: "~/.ssh/{{ ssh_key_name }}.pub"
  register: ssh_public_key
  delegate_to: localhost
  run_once: true

# 4. Créer le répertoire .ssh pour l'utilisateur sur les machines cibles
- name: Créer le répertoire .ssh pour l'utilisateur
  file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
  become: yes

# 5. Copier la clé publique sur les machines cibles dans le fichier authorized_keys
- name: Copier la clé publique SSH dans authorized_keys
  copy:
    content: "{{ ssh_public_key['content'] | b64decode }}"
    dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0600'
  become: yes

# 6. S'assurer que le service SSH est bien configuré pour les connexions par clé et sécurisé
- name: Désactiver l'authentification par mot de passe
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  become: yes

- name: Désactiver l'accès root via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    backup: yes
  become: yes

# 7. Redémarrer le service SSH pour appliquer les changements
- name: Redémarrer le service SSH
  systemd:
    name: ssh
    state: restarted
    enabled: yes
  become: yes

# 8. Enlever les mdp dans le fichier inventaire
- name: Enlever les mots de passe dans le fichier d'inventaire
  replace:
    path: '{{ inipath }}/inventory.ini'
    regexp: 'ansible_.*password=debian'
    replace: ''
  delegate_to: localhost
  run_once: true
