- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure the hostname is set in /etc/hostname
  lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}"
    create: yes

- name: Ensure the hostname is set in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    create: yes
    state: present