- name: Create the ArgoCD namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: argocd
    kubeconfig:  /home/debian/.kube/config 
  become: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Download the ArgoCD installation manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/install.yaml
  become: yes

- name: Apply the ArgoCD installation manifest
  kubernetes.core.k8s:
    state: present
    namespace: argocd
    src: /tmp/install.yaml
    kubeconfig: /home/debian/.kube/config   
  become: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Patch argocd-server service to use NodePort
  k8s:
    namespace: argocd
    api_version: v1
    kind: Service
    name: argocd-server
    state: present
    kubeconfig: /home/debian/.kube/config
    resource_definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        type: NodePort
        ports:
          - name: http
            port: 80
            targetPort: 80
            NodePort: 30007
            protocol: TCP
  become: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Retrieve the service details
  k8s_info:
    kubeconfig: /home/debian/.kube/config
    kind: Service
    namespace: argocd
    name: argocd-server
  register: service_info
  become: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Display the NodePort for argocd-server
  debug:
    msg: "NodePort for argocd-server is {{ service_info.resources[0].spec.ports[1].nodePort }}"


- name: Apply sync.yml to start deployment 
  kubernetes.core.k8s:
    state: present
    template: sync.yml
    kubeconfig: /home/debian/.kube/config   # Chemin vers kubeconfig sur le nœud maître
  become: yes
  delegate_to: "{{ inventory_hostname }}"
