- name: Install Kubeadm and Kubectl
  apt:
    name: 
      - kubeadm=1.31.*
      - kubectl=1.31.*
    state: present
    update_cache: true

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install the python Kubernetes library
  pip:
    name: kubernetes
    state: present

- name: Check if the cluster is already initialized
  command: kubeadm token list
  register: kubeadm_token_list
  ignore_errors: true

- name: Initialize the cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_host }} --ignore-preflight-errors=all
  when: kubeadm_token_list.rc != 0


- name: Create the .kube directory
  become: yes
  become_user: debian
  file:
    path: "$HOME/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/debian/.kube/config
    remote_src: yes
    owner: debian

- name: Check if pod network is installed
  become: yes
  become_user: debian
  command: kubectl get pods -n kube-system -l k8s-app=calico-node
  register: pod_network_check
  ignore_errors: yes

- name: Install the Pod network
  become: yes
  become_user: debian
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml >> pod_network_setup.log
  args:
    chdir: $HOME
    creates: pod_network_setup.log
  when: "'calico-node' not in pod_network_check.stdout"
