name: CI Pipeline

on:
  push:
    branches:
      - 'releases/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: docker-compose build

    - name: Run tests
      run: docker-compose run --rm tests

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      if: success() # Only tag if previous steps succeeded
      run: docker tag flask-app:latest $DOCKER_USERNAME/flask-app:latest

    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/flask-app:latest